export { default as BackArrowIcon } from './back-arrow';
export { default as BookIcon } from './book';
export { default as ForwardArrowCurvedIcon } from './forward-arrow-curved';
export { default as GitIcon } from './git';
export { default as MoonIcon } from './moon';
export { default as SunIcon } from './sun';
export { default as SearchIcon } from './search';
export { default as NoResultIcon } from './no-result';
export { default as AlgoliaIcon } from './algolia';
